/*
  # Seed Global Exercise Library

  Preloads a practical exercise library organized by muscle_group + muscle_section.
  Equipment values are standardized to one of:
    - dumbbell
    - barbell
    - machine
    - smith machine
    - cables
    - kettlebell
    - body weight

  Uses ON CONFLICT on (name, muscle_group, muscle_section, equipment) to avoid duplicates.
*/

BEGIN;

INSERT INTO public.exercises (name, muscle_group, muscle_section, equipment, created_by)
VALUES
  ('Flat Barbell Bench Press','Chest','Mid Chest','barbell', NULL),
  ('Incline Barbell Bench Press','Chest','Upper Chest','barbell', NULL),
  ('Decline Barbell Bench Press','Chest','Lower Chest','barbell', NULL),
  ('Flat Dumbbell Bench Press','Chest','Mid Chest','dumbbell', NULL),
  ('Incline Dumbbell Bench Press','Chest','Upper Chest','dumbbell', NULL),
  ('Decline Dumbbell Press','Chest','Lower Chest','dumbbell', NULL),
  ('Machine Chest Press','Chest','Mid Chest','machine', NULL),
  ('Incline Machine Chest Press','Chest','Upper Chest','machine', NULL),
  ('Smith Machine Bench Press','Chest','Mid Chest','smith machine', NULL),
  ('Smith Machine Incline Bench Press','Chest','Upper Chest','smith machine', NULL),
  ('Cable Chest Fly','Chest','Mid Chest','cables', NULL),
  ('Low-to-High Cable Fly','Chest','Upper Chest','cables', NULL),
  ('High-to-Low Cable Fly','Chest','Lower Chest','cables', NULL),
  ('Pec Deck Fly','Chest','Mid Chest','machine', NULL),
  ('Push-Up','Chest','Mid Chest','body weight', NULL),
  ('Feet-Elevated Push-Up','Chest','Upper Chest','body weight', NULL),
  ('Chest Dip','Chest','Lower Chest','body weight', NULL),
  ('Dumbbell Pullover','Chest','Upper Chest','dumbbell', NULL),
  ('Cable Pullover','Chest','Upper Chest','cables', NULL),
  ('Pull-Up','Back','Lats','body weight', NULL),
  ('Chin-Up','Back','Lats','body weight', NULL),
  ('Neutral-Grip Pull-Up','Back','Lats','body weight', NULL),
  ('Lat Pulldown','Back','Lats','machine', NULL),
  ('Wide-Grip Lat Pulldown','Back','Lats','machine', NULL),
  ('Close-Grip Lat Pulldown','Back','Lats','machine', NULL),
  ('Single-Arm Lat Pulldown','Back','Lats','cables', NULL),
  ('Seated Cable Row','Back','Mid Back','cables', NULL),
  ('Wide-Grip Seated Cable Row','Back','Mid Back','cables', NULL),
  ('Single-Arm Cable Row','Back','Mid Back','cables', NULL),
  ('Chest-Supported Machine Row','Back','Upper Back','machine', NULL),
  ('Chest-Supported Dumbbell Row','Back','Upper Back','dumbbell', NULL),
  ('One-Arm Dumbbell Row','Back','Lats','dumbbell', NULL),
  ('Bent-Over Barbell Row','Back','Upper Back','barbell', NULL),
  ('Pendlay Row','Back','Upper Back','barbell', NULL),
  ('T-Bar Row (Machine)','Back','Mid Back','machine', NULL),
  ('T-Bar Row (Barbell)','Back','Mid Back','barbell', NULL),
  ('Straight-Arm Pulldown','Back','Lats','cables', NULL),
  ('Face Pull','Back','Upper Back','cables', NULL),
  ('Back Extension','Back','Lower Back','body weight', NULL),
  ('Machine Back Extension','Back','Lower Back','machine', NULL),
  ('Roman Chair Back Extension','Back','Lower Back','body weight', NULL),
  ('Good Morning','Back','Lower Back','barbell', NULL),
  ('Deadlift','Back','Lower Back','barbell', NULL),
  ('Rack Pull','Back','Lower Back','barbell', NULL),
  ('Kettlebell Swing','Back','Lower Back','kettlebell', NULL),
  ('Seated Dumbbell Shoulder Press','Shoulders','Front Delts','dumbbell', NULL),
  ('Standing Dumbbell Shoulder Press','Shoulders','Front Delts','dumbbell', NULL),
  ('Barbell Overhead Press','Shoulders','Front Delts','barbell', NULL),
  ('Smith Machine Shoulder Press','Shoulders','Front Delts','smith machine', NULL),
  ('Machine Shoulder Press','Shoulders','Front Delts','machine', NULL),
  ('Arnold Press','Shoulders','Front Delts','dumbbell', NULL),
  ('Dumbbell Lateral Raise','Shoulders','Side Delts','dumbbell', NULL),
  ('Cable Lateral Raise','Shoulders','Side Delts','cables', NULL),
  ('Machine Lateral Raise','Shoulders','Side Delts','machine', NULL),
  ('Upright Row','Shoulders','Side Delts','barbell', NULL),
  ('Dumbbell Front Raise','Shoulders','Front Delts','dumbbell', NULL),
  ('Cable Front Raise','Shoulders','Front Delts','cables', NULL),
  ('Rear Delt Fly (Dumbbell)','Shoulders','Rear Delts','dumbbell', NULL),
  ('Reverse Pec Deck','Shoulders','Rear Delts','machine', NULL),
  ('Cable Rear Delt Fly','Shoulders','Rear Delts','cables', NULL),
  ('Face Pull (Rear Delt Focus)','Shoulders','Rear Delts','cables', NULL),
  ('Shrug (Dumbbell)','Shoulders','Traps','dumbbell', NULL),
  ('Shrug (Barbell)','Shoulders','Traps','barbell', NULL),
  ('Machine Shrug','Shoulders','Traps','machine', NULL),
  ('Farmer''s Carry','Shoulders','Traps','kettlebell', NULL),
  ('Barbell Curl','Arms','Biceps','barbell', NULL),
  ('EZ-Bar Curl','Arms','Biceps','barbell', NULL),
  ('Dumbbell Curl','Arms','Biceps','dumbbell', NULL),
  ('Incline Dumbbell Curl','Arms','Biceps','dumbbell', NULL),
  ('Hammer Curl','Arms','Biceps','dumbbell', NULL),
  ('Cross-Body Hammer Curl','Arms','Biceps','dumbbell', NULL),
  ('Cable Curl','Arms','Biceps','cables', NULL),
  ('Rope Hammer Curl','Arms','Biceps','cables', NULL),
  ('Preacher Curl (Machine)','Arms','Biceps','machine', NULL),
  ('Preacher Curl (Barbell)','Arms','Biceps','barbell', NULL),
  ('Concentration Curl','Arms','Biceps','dumbbell', NULL),
  ('Spider Curl','Arms','Biceps','barbell', NULL),
  ('Chin-Up (Biceps Emphasis)','Arms','Biceps','body weight', NULL),
  ('Cable Triceps Pushdown','Arms','Triceps','cables', NULL),
  ('Rope Triceps Pushdown','Arms','Triceps','cables', NULL),
  ('Overhead Cable Triceps Extension','Arms','Triceps','cables', NULL),
  ('Skull Crushers','Arms','Triceps','barbell', NULL),
  ('EZ-Bar Skull Crushers','Arms','Triceps','barbell', NULL),
  ('Dumbbell Skull Crushers','Arms','Triceps','dumbbell', NULL),
  ('Close-Grip Bench Press','Arms','Triceps','barbell', NULL),
  ('Dip (Triceps Focus)','Arms','Triceps','body weight', NULL),
  ('Machine Triceps Extension','Arms','Triceps','machine', NULL),
  ('Kickback','Arms','Triceps','dumbbell', NULL),
  ('JM Press','Arms','Triceps','barbell', NULL),
  ('Diamond Push-Up','Arms','Triceps','body weight', NULL),
  ('Wrist Curl (Dumbbell)','Arms','Forearms','dumbbell', NULL),
  ('Wrist Curl (Barbell)','Arms','Forearms','barbell', NULL),
  ('Reverse Curl','Arms','Forearms','barbell', NULL),
  ('Reverse Dumbbell Curl','Arms','Forearms','dumbbell', NULL),
  ('Farmer''s Carry (Forearm Focus)','Arms','Forearms','kettlebell', NULL),
  ('Plate Pinch Hold','Arms','Forearms','body weight', NULL),
  ('Back Squat','Legs','Quads','barbell', NULL),
  ('Front Squat','Legs','Quads','barbell', NULL),
  ('Goblet Squat','Legs','Quads','dumbbell', NULL),
  ('Hack Squat (Machine)','Legs','Quads','machine', NULL),
  ('Leg Press','Legs','Quads','machine', NULL),
  ('Smith Machine Squat','Legs','Quads','smith machine', NULL),
  ('Split Squat','Legs','Quads','dumbbell', NULL),
  ('Bulgarian Split Squat','Legs','Quads','dumbbell', NULL),
  ('Walking Lunge','Legs','Quads','dumbbell', NULL),
  ('Reverse Lunge','Legs','Quads','dumbbell', NULL),
  ('Step-Up','Legs','Quads','dumbbell', NULL),
  ('Leg Extension','Legs','Quads','machine', NULL),
  ('Sissy Squat','Legs','Quads','body weight', NULL),
  ('Romanian Deadlift','Legs','Hamstrings','barbell', NULL),
  ('Dumbbell Romanian Deadlift','Legs','Hamstrings','dumbbell', NULL),
  ('Stiff-Leg Deadlift','Legs','Hamstrings','barbell', NULL),
  ('Good Morning (Hamstring Focus)','Legs','Hamstrings','barbell', NULL),
  ('Lying Leg Curl','Legs','Hamstrings','machine', NULL),
  ('Seated Leg Curl','Legs','Hamstrings','machine', NULL),
  ('Nordic Hamstring Curl','Legs','Hamstrings','body weight', NULL),
  ('Hip Thrust','Legs','Glutes','barbell', NULL),
  ('Smith Machine Hip Thrust','Legs','Glutes','smith machine', NULL),
  ('Glute Bridge','Legs','Glutes','body weight', NULL),
  ('Cable Glute Kickback','Legs','Glutes','cables', NULL),
  ('Machine Glute Kickback','Legs','Glutes','machine', NULL),
  ('Kettlebell Swing (Glute Focus)','Legs','Glutes','kettlebell', NULL),
  ('Sumo Deadlift','Legs','Glutes','barbell', NULL),
  ('Cable Pull-Through','Legs','Glutes','cables', NULL),
  ('Standing Calf Raise','Legs','Calves','machine', NULL),
  ('Seated Calf Raise','Legs','Calves','machine', NULL),
  ('Single-Leg Calf Raise','Legs','Calves','body weight', NULL),
  ('Calf Raise (Smith Machine)','Legs','Calves','smith machine', NULL),
  ('Donkey Calf Raise','Legs','Calves','machine', NULL),
  ('Hip Adduction','Legs','Adductors','machine', NULL),
  ('Hip Abduction','Legs','Abductors','machine', NULL),
  ('Plank','Core','Abs','body weight', NULL),
  ('Side Plank','Core','Obliques','body weight', NULL),
  ('Hanging Leg Raise','Core','Abs','body weight', NULL),
  ('Captain''s Chair Leg Raise','Core','Abs','machine', NULL),
  ('Cable Crunch','Core','Abs','cables', NULL),
  ('Machine Crunch','Core','Abs','machine', NULL),
  ('Russian Twist','Core','Obliques','kettlebell', NULL),
  ('Woodchop','Core','Obliques','cables', NULL),
  ('Pallof Press','Core','Core Stability','cables', NULL),
  ('Ab Wheel Rollout','Core','Abs','body weight', NULL),
  ('Dead Bug','Core','Core Stability','body weight', NULL),
  ('Bird Dog','Core','Core Stability','body weight', NULL),
  ('Reverse Crunch','Core','Abs','body weight', NULL),
  ('Bicycle Crunch','Core','Abs','body weight', NULL),
  ('Back Extension (Core)','Core','Lower Back','body weight', NULL),
  ('Burpee','Full Body','Full Body','body weight', NULL),
  ('Kettlebell Clean and Press','Full Body','Full Body','kettlebell', NULL),
  ('Kettlebell Snatch','Full Body','Full Body','kettlebell', NULL),
  ('Thruster','Full Body','Full Body','barbell', NULL),
  ('Dumbbell Thruster','Full Body','Full Body','dumbbell', NULL),
  ('Mountain Climber','Cardio','Cardio','body weight', NULL)
ON CONFLICT (name, muscle_group, muscle_section, equipment) DO NOTHING;

COMMIT;